[project]
authors = ["Alistair Miles <alimanfoo@googlemail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "data"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pip = "*"

[pypi-dependencies]
jupyterlab = "*"
ipykernel = "*"
malariagen-data = "*"
pixi-kernel = "*"
biopython = "*"
scikit-bio = "*"
biotite = "*"
nbformat = "*"
anjl = "*"
memory-profiler = "*"
