[project]
authors = ["Alistair Miles <alimanfoo@googlemail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "docs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
mystmd = ">=1.3.12,<2"

[pypi-dependencies]
anjl = ">=0.8.0, <0.9"
jupyterlab = ">=4.2.5, <5"
nbconvert = ">=7.16.4, <8"
ipykernel = ">=6.29.5, <7"
pixi-kernel = ">=0.5.1, <0.6"
jupyterlab-myst = ">=2.4.2, <3"
