[project]
authors = ["Alistair Miles <alimanfoo@googlemail.com>"]
channels = ["conda-forge"]
description = "anjl documentation"
name = "anjl-docs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
mystmd = ">=1.3.12,<2"

[pypi-dependencies]
anjl = "*"
jupyterlab = "*"
nbconvert = "*"
ipykernel = "*"
pixi-kernel = "*"
jupyterlab-myst = "*"
