name: release
on:
    push:
        tags:
            - 'v*.*.*'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: Install poetry
              run: |
                pipx install poetry
                pipx inject poetry "poetry-dynamic-versioning[plugin]"

            - name: Setup python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'
                  cache: 'poetry'

            - name: Configure poetry
              run: |
                poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

            - name: Build package
              run: poetry build

            - name: Publish to PyPI
              run: poetry publish
